### ISSUE TITLE
專案名稱誤判成google文件

### ISSUE THREAD

**Issue by sih4sing5hong5** [hackfoldr/hackfoldr#67]
我創的專案名子比較長
[tai5-uan5_gian5-gi2_gi2-liau7_phing5-thai5](http://hackfoldr.org/tai5-uan5_gian5-gi2_gi2-liau7_phing5-thai5)
編輯ethercalc沒辦法改到hackfoldr

我看js去抓google 文件
這邊有辦法用一些正規表示法去區分兩者嗎？

**Comment by audreyt** [comment]
Google 文件剛好也用 [-\w] 的字元集...

也許考慮用 `gian5-gi2_gi2-liau7_phing5-thai5` ?

**Comment by sih4sing5hong5** [comment]
那這樣就無法度了

我縮短專案名好了XD
