### ISSUE TITLE
無法進入目錄編輯界面（ethercalc.org），只能進入編輯歷史

### ISSUE THREAD

**Issue by shangkuanlc** [hackfoldr/hackfoldr#75]
我發覺這兩天想要進入[編輯目錄的頁面](https://ethercalc.org/HCD)時，並無法成功，一直出現「Disconnected from server. Reconnecting....」，頂多進入[編輯歷史](https://ethercalc.org/log/?HCD)的頁面。不知道是哪邊出問題。

**Comment by jessy1092** [comment]
ethercalc 維修中，目前只能唯讀

ref. https://logbot.g0v.tw/channel/g0v.tw/2016-04-13#11

**Comment by audreyt** [comment]
已經倒回 4/4 的備份（再晚的 Linode 無法取得）。

**Comment by shangkuanlc** [comment]
感謝修復 orz
